SportsPro/Models/Incident.cs
namespace SportsPro.Models
{
    public class Incident
    {
		public int IncidentID { get; set; }
		public string Title { get; set; } = string.Empty;
        public string Description { get; set; } = string.Empty;
        public DateTime DateOpened { get; set; } = DateTime.Now;
        public DateTime? DateClosed { get; set; } = null;

		public int CustomerID { get; set; }                   // foreign key property
		public Customer? Customer { get; set; } = null!;       // navigation property

		public int ProductID { get; set; }                    // foreign key property
		public Product? Product { get; set; } = null!;         // navigation property

		public int TechnicianID { get; set; }                 // foreign key property 
		public Technician? Technician { get; set; } = null!;   // navigation property

		
	}
}

SportsPro/Controllers/IncidentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SportsPro.Models;

namespace SportsPro.Controllers
{
    public class IncidentController : Controller
    {
        private readonly SportsProContext _context;

        public IncidentController(SportsProContext context)
        {
            _context = context;
        }

        // GET: Incident
        public async Task<IActionResult> Index()
        {
            var sportsProContext = _context.Incidents.Include(i => i.Customer).Include(i => i.Product).Include(i => i.Technician);
            return View(await sportsProContext.ToListAsync());
        }

        // GET: Incident/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var incident = await _context.Incidents
                .Include(i => i.Customer)
                .Include(i => i.Product)
                .Include(i => i.Technician)
                .FirstOrDefaultAsync(m => m.IncidentID == id);
            if (incident == null)
            {
                return NotFound();
            }

            return View(incident);
        }

        // GET: Incident/Create
          public IActionResult Create()
        {
            // Here we assume that Customer has a FullName property
            // If not, you can use "FirstName" or combine them in the SelectList constructor.
            ViewData["CustomerID"] = new SelectList(_context.Customers, "CustomerID", "FullName");
            // For products, display the product Name
            ViewData["ProductID"] = new SelectList(_context.Products, "ProductID", "Name");
            // For technicians, display the technician Name
            ViewData["TechnicianID"] = new SelectList(_context.Technicians, "TechnicianID", "Name");
            return View();
        }
        // POST: Incident/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
  [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IncidentID,Title,Description,DateOpened,DateClosed,CustomerID,ProductID,TechnicianID")] Incident incident)
        {
            if (ModelState.IsValid)
            {
                _context.Add(incident);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(List));
            }
            // Recreate the select lists if model state is invalid
           ViewData["CustomerID"] = new SelectList(_context.Customers, "CustomerID", "FullName", incident.CustomerID);
ViewData["ProductID"] = new SelectList(_context.Products, "ProductID", "Name", incident.ProductID);
ViewData["TechnicianID"] = new SelectList(_context.Technicians, "TechnicianID", "Name", incident.TechnicianID);
   return View(incident);
        }

        // GET: Incident/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var incident = await _context.Incidents.FindAsync(id);
            if (incident == null)
            {
                return NotFound();
            }
            ViewData["CustomerID"] = new SelectList(_context.Customers, "CustomerID", "CustomerID", incident.CustomerID);
            ViewData["ProductID"] = new SelectList(_context.Products, "ProductID", "ProductID", incident.ProductID);
            ViewData["TechnicianID"] = new SelectList(_context.Technicians, "TechnicianID", "TechnicianID", incident.TechnicianID);
            return View(incident);
        }

        // POST: Incident/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IncidentID,Title,Description,DateOpened,DateClosed,CustomerID,ProductID,TechnicianID")] Incident incident)
        {
            if (id != incident.IncidentID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(incident);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!IncidentExists(incident.IncidentID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(List));
            }
            ViewData["CustomerID"] = new SelectList(_context.Customers, "CustomerID", "CustomerID", incident.CustomerID);
            ViewData["ProductID"] = new SelectList(_context.Products, "ProductID", "ProductID", incident.ProductID);
            ViewData["TechnicianID"] = new SelectList(_context.Technicians, "TechnicianID", "TechnicianID", incident.TechnicianID);
            return View(incident);
        }

        // GET: Incident/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var incident = await _context.Incidents
                .Include(i => i.Customer)
                .Include(i => i.Product)
                .Include(i => i.Technician)
                .FirstOrDefaultAsync(m => m.IncidentID == id);
            if (incident == null)
            {
                return NotFound();
            }

            return View(incident);
        }

        // POST: Incident/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var incident = await _context.Incidents.FindAsync(id);
            if (incident != null)
            {
                _context.Incidents.Remove(incident);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(List));
        }
         public async Task<IActionResult> List(){
            var incidents = await _context.Incidents.ToListAsync();
            return View(incidents);
        }

        private bool IncidentExists(int id)
        {
            return _context.Incidents.Any(e => e.IncidentID == id);
        }
        public async Task<IActionResult> Unassigned()
{
    var incidents = await _context.Incidents
        .Include(i => i.Customer)
        .Include(i => i.Product)
        .Include(i => i.Technician)
        .Where(i => i.TechnicianID == null || i.TechnicianID == -1)
        .ToListAsync();

    return View("List", incidents);
}

public async Task<IActionResult> Open()
{
    var incidents = await _context.Incidents
        .Include(i => i.Customer)
        .Include(i => i.Product)
        .Include(i => i.Technician)
        .Where(i => i.DateClosed == null)
        .ToListAsync();

    return View("List", incidents);
}

    }
}

SportsPro/Views/Incident/Create.cshtml
@model SportsPro.Models.Incident
@{
    Layout = "_Layout";
    ViewData["Title"] = "Create Incident";
}

<h2>Create Incident</h2>
<hr />
<div class="row">
    <div class="col-md-6">
        <form asp-action="Create" method="post">
            @Html.AntiForgeryToken()
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group mb-3">
                <label asp-for="Title" class="form-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label asp-for="Description" class="form-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label asp-for="DateOpened" class="form-label"></label>
                <input asp-for="DateOpened" class="form-control" type="date" />
                <span asp-validation-for="DateOpened" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label asp-for="DateClosed" class="form-label"></label>
                <input asp-for="DateClosed" class="form-control" type="date" />
                <span asp-validation-for="DateClosed" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label asp-for="CustomerID" class="form-label"></label>
                <select asp-for="CustomerID" class="form-control" asp-items="ViewBag.CustomerID"></select>
            </div>

            <div class="form-group mb-3">
                <label asp-for="ProductID" class="form-label"></label>
                <select asp-for="ProductID" class="form-control" asp-items="ViewBag.ProductID"></select>
            </div>

            <div class="form-group mb-3">
                <label asp-for="TechnicianID" class="form-label"></label>
                <select asp-for="TechnicianID" class="form-control" asp-items="ViewBag.TechnicianID"></select>
            </div>

            <button type="submit" class="btn btn-primary">Create</button>
            <a asp-action="List" class="btn btn-secondary">Back to List</a>
        </form>
    </div>
</div>

SportsPro/Views/Incident/Delete.cshtml
@model SportsPro.Models.Incident

@{
  Layout = "_Layout";}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Incident</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateOpened)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateOpened)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateClosed)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateClosed)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Customer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Customer.CustomerID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Product)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Product.ProductID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Technician)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Technician.TechnicianID)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IncidentID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>
</body>
</html>

SportsPro/Views/Incident/Details.cshtml
@model SportsPro.Models.Incident

@{
  Layout = "_Layout";}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>

<div>
    <h4>Incident</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateOpened)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateOpened)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateClosed)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateClosed)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Customer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Customer.CustomerID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Product)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Product.ProductID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Technician)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Technician.TechnicianID)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.IncidentID" class="btn btn-primary">Edit</a> |
    <a asp-action="List" class="btn btn-secondary">Back to List</a>
</div>
</body>
</html>

SportsPro/Views/Incident/Edit.cshtml
@model SportsPro.Models.Incident

@{
    Layout = "_Layout";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>

<h4>Incident</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IncidentID" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOpened" class="control-label"></label>
                <input asp-for="DateOpened" class="form-control" />
                <span asp-validation-for="DateOpened" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateClosed" class="control-label"></label>
                <input asp-for="DateClosed" class="form-control" />
                <span asp-validation-for="DateClosed" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerID" class="control-label"></label>
                <select asp-for="CustomerID" class="form-control" asp-items="ViewBag.CustomerID"></select>
                <span asp-validation-for="CustomerID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductID" class="control-label"></label>
                <select asp-for="ProductID" class="form-control" asp-items="ViewBag.ProductID"></select>
                <span asp-validation-for="ProductID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TechnicianID" class="control-label"></label>
                <select asp-for="TechnicianID" class="form-control" asp-items="ViewBag.TechnicianID"></select>
                <span asp-validation-for="TechnicianID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
                    <a asp-action="List" class="btn btn-secondary">Back to List</a>
            </div>
        </form>
    </div>
</div>

<div>

</div>

</body>
</html>

SportsPro/Views/Incident/Index.cshtml
@model IEnumerable<SportsPro.Models.Incident>

@{
  Layout = "_Layout";}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateOpened)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateClosed)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Customer)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Product)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Technician)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateOpened)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateClosed)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Customer.CustomerID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Product.ProductID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Technician.TechnicianID)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.IncidentID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.IncidentID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.IncidentID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
</body>
</html>

SportsPro/Views/Incident/List.cshtml
@model IEnumerable<SportsPro.Models.Incident>
@{
    Layout = "_Layout";
    ViewData["Title"] = "Incident Manager";

    // Retrieve current action name from RouteData
    var currentAction = ViewContext.RouteData.Values["action"] as string;
}

<h2>Incident Manager</h2>

<!-- Filter links (Bootstrap Pills) -->
<ul class="nav nav-pills mb-3">
    <!-- All incidents -->
    <li class="nav-item">
        <a class="text-primary nav-link @(currentAction == "List" ? "active" : "")"
           asp-action="List" asp-controller="Incident">
            All incidents
        </a>
    </li>
    <!-- Unassigned incidents -->
    <li class="nav-item">
        <a class="text-primary nav-link @(currentAction == "Unassigned" ? "active" : "")"
           asp-action="Unassigned" asp-controller="Incident">
            Unassigned incidents
        </a>
    </li>
    <!-- Open incidents -->
    <li class="nav-item">
        <a class="text-primary nav-link @(currentAction == "Open" ? "active" : "")"
           asp-action="Open" asp-controller="Incident">
            Open incidents
        </a>
    </li>
</ul>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Title</th>
            <th>Customer</th>
            <th>Product</th>
            <th>Date Opened</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null && Model.Any())
        {
            foreach (var inc in Model)
            {
                <tr>
                    <td>@inc.Title</td>
                    <td>@inc.Customer?.FullName</td>
                    <td>@inc.Product?.Name</td>
                    <td>@inc.DateOpened.ToShortDateString()</td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@inc.IncidentID" class="btn btn-primary">
                            Edit
                        </a>
                    </td>
                    <td>
                        <a asp-action="Delete" asp-route-id="@inc.IncidentID" class="btn btn-danger">
                            Delete
                        </a>
                    </td>
                </tr>
            }
        }
        else
        {
            <tr>
                <td colspan="6" class="text-center">No incidents found.</td>
            </tr>
        }
    </tbody>
</table>

<a asp-action="Create" class="btn btn-success">Add Incident</a>